// <auto-generated />
namespace ClinicAppDataBase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class OnModelCreatingContextChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OnModelCreatingContextChange));
        
        string IMigrationMetadata.Id
        {
            get { return "202106121924342_OnModelCreatingContextChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
