// <auto-generated />
namespace ClinicAppDataBase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AppointmentNameAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AppointmentNameAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "202106131836250_AppointmentNameAdd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
